console.log('hello, world');
var h1 = document.querySelector('h1');
console.log(h1);
console.dir(h1);
var idExplanation = document.querySelector('#explanation');
console.log(idExplanation);
console.dir(idExplanation);
var classHint = document.querySelector('.hint');
console.log(classHint);
console.dir(classHint);
var nodeList = document.querySelectorAll('p');
console.log(nodeList);
var exampleLink = document.querySelectorAll('.example-link');
console.log(exampleLink);
